### ISSUE TITLE
相关技术友情链接

### ISSUE THREAD

**Issue by qiujuer** [qiujuer/iTalker#1]
在这里，附上课程使用的相关技术，部分文章是学生自己的分享，这里一起搬运过来放一起了～

**Comment by qiujuer** [comment]
## IM即时通讯项目讲解(一)--实现类似qq微信表情面板无缝切换
![image](https://user-images.githubusercontent.com/5687320/28107265-8e552e2a-6719-11e7-9137-301752013bc6.png)

http://www.jianshu.com/p/95222eeb35a4

**Comment by SwordAbuse** [comment]
https://github.com/SwordAbuse/Tutorial/issues
