### ISSUE TITLE
关于图片选择弹出框底部显示不全的问题

### ISSUE THREAD

**Issue by chen-xin93** [qiujuer/iTalker#10]
其实只要设置下GalleryView的setMarginBottom就可以了
经群里的同学提示，图片选择弹出框被隐藏部分的高度与顶部AppBarLayout的高度一样
这样问题就简单了，获取到AppBarLayout的高度，设置marginBottom就可以了。代码如下：
        //获取AppBarLayout
        appbar = (AppBarLayout) root.findViewById(R.id.appbar);
        //获取AppBarLayout的控件高度
        ViewTreeObserver vto = appbar.getViewTreeObserver();
        vto.addOnPreDrawListener(new ViewTreeObserver.OnPreDrawListener() {
            public boolean onPreDraw() {
                //高度
                int height = appbar.getMeasuredHeight();
                Log.e("1234", "height = " + height);
                CoordinatorLayout.LayoutParams layoutParams = (CoordinatorLayout.LayoutParams) galleryView.getLayoutParams();
                layoutParams.setMargins(0, 0, 0, height);//动态设置margin
                return true;
            }
        });

当然，也可以直接在xml布局文件里面设置GalleryView，加上一定的marginBottom就好，更加简单粗暴。。。

ps：小白一枚，跟我一样的小白可以参考一下！！！

**Comment by qiujuer** [comment]
给你修改一下格式

**Comment by qiujuer** [comment]
其实只要设置下GalleryView的setMarginBottom就可以了。

经群里的同学提示，图片选择弹出框被隐藏部分的高度与顶部AppBarLayout的高度一样；这样问题就简单了，获取到AppBarLayout的高度，设置marginBottom就可以了。

代码如下：

```java
       //获取AppBarLayout
        appbar = (AppBarLayout) root.findViewById(R.id.appbar);
        //获取AppBarLayout的控件高度
        ViewTreeObserver vto = appbar.getViewTreeObserver();
        vto.addOnPreDrawListener(new ViewTreeObserver.OnPreDrawListener() {
            public boolean onPreDraw() {
                //高度
                int height = appbar.getMeasuredHeight();
                Log.e("1234", "height = " + height);
                CoordinatorLayout.LayoutParams layoutParams = (CoordinatorLayout.LayoutParams) galleryView.getLayoutParams();
                layoutParams.setMargins(0, 0, 0, height);//动态设置margin
                return true;
            }
        });

```
 
当然，也可以直接在xml布局文件里面设置GalleryView，加上一定的marginBottom就好，更加简单粗暴。。。
