### ISSUE TITLE
慕聊录音界面出现Crash解决方案

### ISSUE THREAD

**Issue by qiujuer** [qiujuer/iTalker#11]
### 问题描述
软件添加好布局后，进入聊天页面，初始化录音界面时触发Crash异常；表现错误为：
![image](https://user-images.githubusercontent.com/5687320/35212915-be63fa04-ff96-11e7-9be9-8d3615999a87.png)
该问题是由于Lame库在进行初始化时出现的SO代码异常问题，是由于C语音部分代码异常导致返回的指针错误。该问题是Runtime异常，由于没有进行捕获所以会直接导致Crash。

#### 第一步
打开项目根目录build文件：
![image](https://user-images.githubusercontent.com/5687320/35213031-294b4570-ff97-11e7-9534-97a06ff5a427.png)

并修改对应版本如下：
![image](https://user-images.githubusercontent.com/5687320/35213048-42fefc00-ff97-11e7-9b11-394556acf20c.png)

- Lame版本：1.2.0
- Support：27.0.2 （由于依赖的简单注解库提升，你提升后遇到问题可以直接安装版本即可）
![image](https://user-images.githubusercontent.com/5687320/35213125-81d10806-ff97-11e7-90d7-77f3a6867af6.png)

#### 第二步
打开主项目build文件：
![image](https://user-images.githubusercontent.com/5687320/35213152-9dd533c4-ff97-11e7-8f90-d6ee4589b891.png)

添加NDK过滤，由于其他库有全NDK，会有可能导致手机识别失败的情况。
![image](https://user-images.githubusercontent.com/5687320/35213190-bd98adb2-ff97-11e7-8726-ea9077dfb694.png)

路径：android->defaultConfig->ndk->abiFilters

```java
        ndk {
            abiFilters "x86", "x86_64", "arm64-v8a", "armeabi-v7a", 'armeabi'
        }
```

#### 第三步
打开**AudioRecordHelper**类，移除数组中的：`192000`
![image](https://user-images.githubusercontent.com/5687320/35213395-70744de2-ff98-11e7-8377-9d196ff2f85b.png)
该问题是因为，Lame框架其实并不支持192000采样率的分析压缩，会导致数组溢出。目前来说没法解决，需要接手Lame核心代码修改。

#### 第四步
同样在当前类中修改，搜索方法 `record()`：
![image](https://user-images.githubusercontent.com/5687320/35213488-c1efdcf4-ff98-11e7-87fd-0bfaffc8e1af.png)

增加错误的捕获，减少可能出现的Crash情况，并且提示当前的错误代码信息。

### End
好了，重新rebuild一次代码，重新运行吧；此时应该是OK了哈。
多谢大家对课程的支持，感谢～

**Comment by ljr7822** [comment]
老师，java.lang.RuntimeException: Initialize Lame failed:-5476376668999670400还是有错

**Comment by Geek-Spirit** [comment]
> 老师，java.lang.RuntimeException: Initialize Lame failed:-5476376668999670400还是有错

我也是这个错误,有解决吗?
