### ISSUE TITLE
进入页面闪退解决方案

### ISSUE THREAD

**Issue by qiujuer** [qiujuer/iTalker#12]
![image](https://user-images.githubusercontent.com/5687320/35255874-1e9edab6-002c-11e8-9878-adf5ccecc099.png)
如图所示，有时候进入界面出现闪退情况，仔细一看说的是XML初始化的时候出现Crash异常。
粗看一下以为是 **AudioRecordView** 控件问题，但是其实并不是，我们往错误下面看一下：
![image](https://user-images.githubusercontent.com/5687320/35255921-51310bb6-002c-11e8-86aa-acf1d1156bd6.png)
哎，可以看见是 `net.qiujuer.genius.ui.widget.FloatActionButton` 问题；如果你可以调试，可以进入调试看看，会发现其实是一个资源Id冲突导致的问题。

该问题已在GeniusUi库中升级得到解决，请更改版本后rebuild就好。
![image](https://user-images.githubusercontent.com/5687320/35256130-4ec1a416-002d-11e8-87a7-54e87a6e710f.png)

**Comment by passerbyYSQ** [comment]
遇到这个问题。来mark一下
