### ISSUE TITLE
画廊界面出现权限崩溃异常

### ISSUE THREAD

**Issue by qiujuer** [qiujuer/iTalker#13]
## 现象触发：
- Android 7.0 部分手机因为FileProvider崩溃
- Android 6.0 因为动态权限崩溃
- 进入画廊页面

## 现象截图：
![image](https://user-images.githubusercontent.com/5687320/35671914-ba032780-0777-11e8-8004-cf7696309e8e.png)

## 找问题
```java
java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=5799, uid=10019 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
```
核心的问题，从代码中可以看出就是说权限错误；那么这个问题如何解决？？
当然是授权啊，授权并不是说在Manifest中添加就行；在Android6.0以后需要进行动态权限获取；具体的代码课程中有讲解，这里简单贴出一下：
```java
boolean hasAll = PermissionsFragment.checkNetworkPermissions(this, getSupportFragmentManager())
        && PermissionsFragment.checkReadStoragePermissions(this, getSupportFragmentManager())
        &&PermissionsFragment.checkRecordPermissions(this, getSupportFragmentManager())
        &&PermissionsFragment.checkWriteStorageExternalPermissions(this, getSupportFragmentManager());
```
调用权限页面进行权限检测，当具有对应权限时再打开画廊界面即可。

> PS:PermissionsFragment 是后面章节会讲解的动态权限管理器。

此时一般而言崩溃已经解决好了，这是因为动态权限引起的崩溃；如果你还没有学到动态权限的章节出现的问题，那么请进入系统设置-应用管理-找到APP-把所有的权限都打开-然后进入调试即可。

## 题外话

在部分同学的设备上出现了Android7.0 权限崩溃，其实课程的画廊界面并没有使用到7.0的东西，按理说应该不会崩溃，但是既然有同学反馈；那么我们来说说解决办法。

**Comment by qiujuer** [comment]
![image](https://user-images.githubusercontent.com/5687320/35672768-7ed04938-077a-11e8-9702-d16c55347f97.png)

**Comment by qiujuer** [comment]
完成如上配置之后，咱们进入到代码修改环节，咱们把之前出错部分的代码修改如下：
![image](https://user-images.githubusercontent.com/5687320/35713758-0f99cff0-0804-11e8-93f3-22d9d585dd61.png)
```java
    File file = new File(paths[0]);
    //Uri uri = Uri.fromFile(file);

    Uri uri = FileProvider.getUriForFile(TestActivity.this,
            getApplicationContext().getPackageName() + ".provider",
            file);
    intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);

    intent.putExtra(MediaStore.EXTRA_OUTPUT, uri);
    startActivityForResult(intent, 1);
```

可以发现，我们把之前的Uri操作换成了使用FileProvider去操作的方式，并且我们设置了咱们FileProvider的标示：**getApplicationContext().getPackageName() + ".provider"**；这和咱们Manifest定义的一样。

然后此时运行-选择图片-会发现跳转到了拍摄页面-此时你拍摄一张照片-返回-你会发现剪切页面的图片是你刚刚拍摄的页面了，这就是在拍摄时存储照片到你设置的页面路径下。

## 总结
当A APP - B APP交互时，不能直接把路径丢给B，因为A可能有权限，但是B不一定有权限，那么此时我们通过A的FileProvider为桥梁进行操作，B的返回也是通过FileProvider操作那么就不存在这个问题了。

这其实是系统安全性的一个必经的过程。

**Comment by ganguanglong** [comment]
👍  ，支持🇨🇳  好 👨‍🏫
