### ISSUE TITLE
在录制语音结束后，将Temp文件重命名成其它文件使用java renameTo方法总是返回false。

### ISSUE THREAD

**Issue by LiMedici** [qiujuer/iTalker#14]
if (file.renameTo(audioFile)) {
                    // 通知到聊天界面
                    PanelCallback panelCallback = mCallback;
                    if (panelCallback != null) {
                        panelCallback.onRecordDone(audioFile, time);
                    }
                }

**Comment by qiujuer** [comment]
这里加上断点一次，然后看看两点：

1. file 和 audioFile 的路径是不是在统一个文件夹下面，如果不是则不行
2. audioFile 看看是不是已经有了
