### ISSUE TITLE
画廊控件在XML文件使用时完全没反应

### ISSUE THREAD

**Issue by GeminiWy** [qiujuer/iTalker#15]
画廊控件在XML文件使用时完全没反应，ActiveFragment页面空白，应该从哪打断点调试呢？

**Comment by qiujuer** [comment]
这个问题建议你进入开发者模式-显示布局边界 功能查看控件是否OK。

另外，建议添加背景颜色，以及强制一个高度的方式来看看是不是有什么问题。
