### ISSUE TITLE
发送聊天信息之后出现ANR异常，且消息发送失败！

### ISSUE THREAD

**Issue by MLLWF** [qiujuer/iTalker#17]
警告日志：![tim 20180316161400](https://user-images.githubusercontent.com/19337282/37510128-0f7c6940-2935-11e8-803f-053ee02aa5dd.png)
引发原因：
![tim 20180316165555](https://user-images.githubusercontent.com/19337282/37511743-ed6b98e8-293a-11e8-9e4a-05147096f033.png)
当发送聊天信息时，需要将聊天信息存储到数据库中(DBHelp#save())，存储完成之后需要通知聊天列表这个观察者进行聊天列表刷新(DBHelp#notifySave())，DBHelp#notifySave()是在beginTransactionAsync开启的事务中执行的，所以此时事务并没有结束而是依然持有着数据库的链接，等到了界面刷新的逻辑ChatFragment#BaseViewHolder#onBind()方法里面时由于Message中的User是懒加载，所以需要重新从数据库中加载User的完成数据，所以需要持有数据库的链接，但是此时数据库的链接被DBHelp#save()#beginTransactionAsync()中的事务持有着，从而造成了死锁！导致界面刷新持续等待着，造成了ANR异常！
解决办法：
![tim 20180316171452](https://user-images.githubusercontent.com/19337282/37512599-8fda1f12-293d-11e8-876d-74c498c29659.png)
将DBHelp#notifySave()的逻辑放到线程池中去异步执行，
这时候DBHelp#save()#beginTransactionAsync()方法就会执行完毕，事务就会完成掉，从而数据库的链接也会释放掉，当界面更新加载User数据时就不需要等待数据库链接，所以就不会形成死锁！

**Comment by qiujuer** [comment]
👍
