### ISSUE TITLE
关于OSS初始化client时AccessKey和AccessKeySecret的设置

### ISSUE THREAD

**Issue by CornPrincess** [qiujuer/iTalker#18]
**由于老师视频是一年前的，现在OSS已经更新了API，以及一些常用设置**
详情可参考官网链接：[https://help.aliyun.com/document_detail/32044.htmlspm=a2c4g.11186623.6.708.5Dcfrk](url)

首先是现在官网推荐使用STS的初始化client方式
![image](https://user-images.githubusercontent.com/31826081/38294782-90270a1c-381e-11e8-9f2e-c1072617d4a8.png)
这里如果按照老师视频里以前老的方法也是可以的，但是AccessKey和AccessKeySecret的设置出现了变化

老师以前是用的控制台里面的AccessKey和AccessKeySecret
![image](https://user-images.githubusercontent.com/31826081/38294850-da916eee-381e-11e8-85f7-e248e1ba49e1.png)

这里在测试时发现这里的key没有权限访问OSS，出现如下error
![image](https://user-images.githubusercontent.com/31826081/38294984-32ccd2e2-381f-11e8-9263-9ce965b926d1.png)

经过尝试发现需要使用OSSjiemian的key才可以
![image](https://user-images.githubusercontent.com/31826081/38294907-028158ec-381f-11e8-9fb0-5d9fd1dfee6d.png)

如果大家也出现同样错误可以尝试使用OSS界面的AccessKey和AccessKeySecret

**Comment by qiujuer** [comment]
👍
