### ISSUE TITLE
课程代码正确导入方式-免404

### ISSUE THREAD

**Issue by qiujuer** [qiujuer/iTalker#19]
> 许多同学都有出现课程导入后出现404错误，或者干脆无法启动起来；鉴于出现频率较高，所以写一篇文章给大家讲讲新的方案。

现象：
1. 访问主页404错误
2. 无法正常启动
3. 访问主页没问题-访问登录注册接口异常

原因：
1. Tomcat目录无权限（[解决方案](https://github.com/qiujuer/iTalker#%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%BF%90%E8%A1%8C%E6%B2%A1%E6%9C%89%E7%9C%8B%E8%A7%81%E6%AC%A2%E8%BF%8E%E7%95%8C%E9%9D%A2)）
2. idea 导入时 gradle 依赖问题，这是最主要的问题点。

对于idea导入的问题，在群里有一份文档指出了方案，但是并不是所有的用户都是这个原因，发现有些同学导入时根本未提示Gradle依赖。

## 新导入方案

首先，导入时选择正确的文件夹：
![image](https://user-images.githubusercontent.com/5687320/38372004-6a5be7aa-3920-11e8-9f23-9336ab8f4570.png)

一定选择到**“Web/iTalker”**上。

**Comment by qiujuer** [comment]
第二步，在导入的首次步骤中，我们直接选择gradle；帮助idea选择，免去识别失败的可能性。
![image](https://user-images.githubusercontent.com/5687320/38372183-cc26885a-3920-11e8-8b46-7a9f3dd0c395.png)

第三步，根据箭头所示的提示进行选择。
![image](https://user-images.githubusercontent.com/5687320/38372269-fb9cd062-3920-11e8-9027-ea56b00ee7ba.png)

重要条件：
1. Use auto-improt 勾选上
2. 经过测试发现，第二个勾选框不必勾选，之前课程之所以勾选是因为我的电脑配置的原因。
3. 关于红色框中的选择：网络充分的同学建议直接使用：“Use default gradle wapper” 的模式；因为可以让idea自己下载最合适的gradle版本。

如果网络不好的同学，也可以选择 **“Use default gradle wapper”**，等进入时查看一下下载的gradle版本，然后使用：https://blog.csdn.net/qiujuer/article/details/77312577 方案下载gradle后，再重新导入设置本地的gradle进行编译即可。

**Comment by qiujuer** [comment]
在导入时底部会有gradle下载与编译的进度，此时不可断开网络和操作；等待即可。
![image](https://user-images.githubusercontent.com/5687320/38372610-d547dac8-3921-11e8-9db1-a44ef57cfcc0.png)

等全部完成后，再点击右上角，运行按钮进行项目运行配置。
![image](https://user-images.githubusercontent.com/5687320/38372655-ecce8c5a-3921-11e8-83d9-452e50641c12.png)

选择Tomcat，如果没有的同学先安装Tomcat，如果还是没有看看是不是你没有在 “+” 的下面完全打开列表。
![image](https://user-images.githubusercontent.com/5687320/38372764-2981a358-3922-11e8-9f6f-65e13bed3cef.png)

其他都无需更改，点击底部**Fix**，这个按钮仅仅在gradle成功的情况下才会自动出现。

![image](https://user-images.githubusercontent.com/5687320/38372842-5a367172-3922-11e8-85db-8513a4be2416.png)

OK，运行即可。

**Comment by qiujuer** [comment]
祝你好运～～ 🍀

**Comment by lhl90** [comment]
666

**Comment by ITerydh** [comment]
出现了fix,但并没有出现war选择项

**Comment by Mimikkogs17** [comment]
我也是点击的fix，没有war选项，最后我直接导入原项目的war文件，运行后还是原项目的界面，而且目录没有webapp文件夹
