### ISSUE TITLE
课程完整代码编译后可能闪退解决方案

### ISSUE THREAD

**Issue by qiujuer** [qiujuer/iTalker#2]
编译：AS3 预览版
现象：直接闪退
![image](https://user-images.githubusercontent.com/5687320/28108936-d659eb10-671f-11e7-88f2-8c29dfd56f4e.png)

BUG提交者：我爱吃各种口味的方便面.

**Comment by qiujuer** [comment]
原因是因为AS3下编译自定义控件时进行了ID重排，而自定义控件FloatActionButton中由于自定义属性index错位，引起的数据错乱，从而引发崩溃。

**Comment by qiujuer** [comment]
解决方案：升级Genius-Android-ui库到：2.0.1 版本即可；也可全部升级Genius-Android库版本：

```
compile "net.qiujuer.genius:ui:2.0.1"
```

项目级别build.gradle:
```
ext {
    geniusVersion = '2.0.1'
}

```

**Comment by GzwJaaaelu** [comment]
感谢及时解决了 Bug，看上去是格式化问题，但其实来源是自定义控件的自定义标签。
