### ISSUE TITLE
服务器端问题

### ISSUE THREAD

**Issue by canliture** [qiujuer/iTalker#26]
服务器端查看存储的时间，总是有8个小时的时差！
解决方案：

查看hibernate.cfg.xml 的jdbc连接数据库的url源码：
  `<property name="connection.url">jdbc:mysql://127.0.0.1:3306/DB_I_T_PUSH?serverTimezone=UTC&amp;useUnicode=true&amp;characterEncoding=utf8&amp;useSSL=false</property>`
其中的serverTimezone的值改为`serverTimezone=Asia/Shanghai`

**Comment by qiujuer** [comment]
👍
