### ISSUE TITLE
第六章跟着教程来的，不过报空指针，hibernate不能正常创建数据库

### ISSUE THREAD

**Issue by IChanr** [qiujuer/iTalker#27]
`HTTP Status 500 – Internal Server Error
Type Exception Report

Message java.lang.NullPointerException

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

javax.servlet.ServletException: java.lang.NullPointerException
	org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:434)
	org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:372)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
Root Cause

java.lang.NullPointerException
	net.qiujuer.web.italker.push.utils.Hib.query(Hib.java:111)
	net.qiujuer.web.italker.push.factory.UserFactory.createUser(UserFactory.java:173)
	net.qiujuer.web.italker.push.factory.UserFactory.register(UserFactory.java:149)
	net.qiujuer.web.italker.push.service.AccountService.test(AccountService.java:22)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	java.lang.reflect.Method.invoke(Unknown Source)
	org.glassfish.jersey.server.internal.routing.SubResourceLocatorRouter$1.run(SubResourceLocatorRouter.java:158)
	org.glassfish.jersey.server.internal.routing.SubResourceLocatorRouter.getResource(SubResourceLocatorRouter.java:178)
	org.glassfish.jersey.server.internal.routing.SubResourceLocatorRouter.apply(SubResourceLocatorRouter.java:109)
	org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:109)
	org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:112)
	org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:112)
	org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:112)
	org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:112)
	org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:92)
	org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:61)
	org.glassfish.jersey.process.internal.Stages.process(Stages.java:197)
	org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:329)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:280)
	org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:316)
	org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1084)
	org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:418)
	org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:372)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
Note The full stack trace of the root cause is available in the server logs.

Apache Tomcat/9.0.13`

**Comment by IChanr** [comment]
这个用的就是课程提供的源码

**Comment by IChanr** [comment]
[https://wx2.sinaimg.cn/large/a5237847gy1fyh3asqq2dj218s0cjaeg.jpg](url)

**Comment by IChanr** [comment]
https://wx2.sinaimg.cn/large/a5237847gy1fyh3asqq2dj218s0cjaeg.jpg

**Comment by qiujuer** [comment]
这个是空指针异常了呀，你调试一下看看这个步骤中那个变量是null的。
另外可以Q群找我一下。
