### ISSUE TITLE
服务器外网部署计划

### ISSUE THREAD

**Issue by qiujuer** [qiujuer/iTalker#3]
部署服务器代码到外网服务器上，并运行APP的步骤。

总的来说我们需要进行如下步骤：
1. 阿里云服务器准备（腾讯也行）
2. 安装MySQL
3. 安装Java环境
4. 安装Tomcat
5. 部署Tomcat
6. Push项目文件到云服务器

共计6个步骤即可～～

**重要重要：**[视频链接](https://pan.baidu.com/s/1i5qXafV) `密码: ngba`

**云服务器促销优惠**
https://s.click.taobao.com/tvw52bw （学生优惠）
https://s.click.taobao.com/x8a42bw （普通）

扫码二维码打开也可以：
![image](https://user-images.githubusercontent.com/5687320/30463627-687fb74c-99ff-11e7-923c-f6a27f431dfa.png)

![image](https://user-images.githubusercontent.com/5687320/30463616-563bf992-99ff-11e7-94e1-52531bbbdb26.png)

**Comment by qiujuer** [comment]
![image](https://user-images.githubusercontent.com/5687320/28110621-8eee5710-6725-11e7-97e3-914f58edc22c.png)
霸气跟上·～～

**Comment by LiTaiyu** [comment]
抢个前排？

**Comment by gwgrisk** [comment]
前排

**Comment by xk009** [comment]
顶顶顶，老司机又发车啦

**Comment by qiujuer** [comment]
## 第一步骤：阿里云服务器开通并配置。

**Comment by qiujuer** [comment]
## 第二步骤：安装MySQL

**Comment by qiujuer** [comment]
第三步骤：安装Java环境

**Comment by qiujuer** [comment]
## 第四步骤：安装Tomcat

**Comment by qiujuer** [comment]
## 第五步骤：部署Tomcat

**Comment by qiujuer** [comment]
## Push项目文件到云服务器
要完成这一步，你需要保证云服务器和你的电脑同时具备scp命令。要知道有没有很简单，执行一下scp命令即可；如果说没找到那就没有了。默认阿里的CentOS是具有的。而Mac电脑也默认具备，Windows下面的Linux可能不具备，你需要通过yum来安装，主要步骤：
1. 给你的环境安装yum插件（也可之间安装）
2. 通过yum安装openssh-clients
```
yum install openssh-clients
```
安装好了之后，就可以尽情的部署了。

**Comment by qiujuer** [comment]
已完结，再次感谢 Sunny.Ti7 同学提供服务器支持。

**Comment by null123dzq** [comment]
点赞👍

**Comment by douya40** [comment]
我能说我比较喜欢Windows的服务器吗？

**Comment by qiujuer** [comment]
@douya40 也是可以的啊；Windows配置还更简单。

**Comment by passerbyYSQ** [comment]
mark

**Comment by YaokunLee** [comment]
点赞！！！
